<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Inventario;

class InventarioSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $items = [
            // COMPONENTES DE HARDWARE
            [
                'codigo' => 'INV-001',
                'nombre' => 'Disco Duro SSD Samsung 500GB',
                'descripcion' => 'Disco de estado sólido Samsung 870 EVO de 500GB, ideal para mejorar el rendimiento del sistema',
                'categoria' => 'Componentes',
                'marca' => 'Samsung',
                'modelo' => '870 EVO',
                'serie' => 'SN123456789',
                'stock_minimo' => 5,
                'stock_actual' => 15,
                'precio_compra' => 45.00,
                'precio_venta' => 65.00,
                'proveedor' => 'Distribuidora ABC',
                'ubicacion' => 'Almacén A, Estante 1',
                'estado' => 'activo',
                'fecha_compra' => '2024-01-15',
                'notas' => 'Producto de alta demanda, mantener stock mínimo'
            ],
            [
                'codigo' => 'INV-002',
                'nombre' => 'Memoria RAM DDR4 8GB',
                'descripcion' => 'Módulo de memoria RAM DDR4 de 8GB, velocidad 3200MHz',
                'categoria' => 'Componentes',
                'marca' => 'Kingston',
                'modelo' => 'Fury Beast',
                'serie' => 'SN987654321',
                'stock_minimo' => 10,
                'stock_actual' => 25,
                'precio_compra' => 25.00,
                'precio_venta' => 35.00,
                'proveedor' => 'Distribuidora XYZ',
                'ubicacion' => 'Almacén A, Estante 2',
                'estado' => 'activo',
                'fecha_compra' => '2024-01-20',
                'notas' => 'Compatible con la mayoría de placas base'
            ],
            [
                'codigo' => 'INV-003',
                'nombre' => 'Memoria RAM DDR4 16GB',
                'descripcion' => 'Módulo de memoria RAM DDR4 de 16GB, velocidad 3200MHz para gaming y trabajo profesional',
                'categoria' => 'Componentes',
                'marca' => 'Corsair',
                'modelo' => 'Vengeance LPX',
                'serie' => 'SN111222333',
                'stock_minimo' => 8,
                'stock_actual' => 12,
                'precio_compra' => 55.00,
                'precio_venta' => 75.00,
                'proveedor' => 'Distribuidora XYZ',
                'ubicacion' => 'Almacén A, Estante 2',
                'estado' => 'activo',
                'fecha_compra' => '2024-02-10',
                'notas' => 'Para equipos de alto rendimiento'
            ],
            [
                'codigo' => 'INV-004',
                'nombre' => 'Disco Duro HDD 1TB',
                'descripcion' => 'Disco duro mecánico Seagate BarraCuda de 1TB, 7200 RPM',
                'categoria' => 'Componentes',
                'marca' => 'Seagate',
                'modelo' => 'BarraCuda',
                'serie' => 'SN444555666',
                'stock_minimo' => 6,
                'stock_actual' => 18,
                'precio_compra' => 35.00,
                'precio_venta' => 50.00,
                'proveedor' => 'Distribuidora ABC',
                'ubicacion' => 'Almacén A, Estante 3',
                'estado' => 'activo',
                'fecha_compra' => '2024-02-15',
                'notas' => 'Almacenamiento secundario confiable'
            ],
            [
                'codigo' => 'INV-005',
                'nombre' => 'Fuente de Poder 650W 80+ Bronze',
                'descripcion' => 'Fuente de poder modular EVGA 650W con certificación 80+ Bronze',
                'categoria' => 'Componentes',
                'marca' => 'EVGA',
                'modelo' => 'BQ 650W',
                'serie' => 'SN777888999',
                'stock_minimo' => 4,
                'stock_actual' => 8,
                'precio_compra' => 75.00,
                'precio_venta' => 105.00,
                'proveedor' => 'Distribuidora Premium',
                'ubicacion' => 'Almacén A, Estante 4',
                'estado' => 'activo',
                'fecha_compra' => '2024-02-20',
                'notas' => 'Fuente modular de alta calidad'
            ],
            [
                'codigo' => 'INV-006',
                'nombre' => 'Placa Base AMD B450',
                'descripcion' => 'Placa base ASUS TUF Gaming B450 para procesadores AMD AM4',
                'categoria' => 'Componentes',
                'marca' => 'ASUS',
                'modelo' => 'TUF Gaming B450M',
                'serie' => 'SN000111222',
                'stock_minimo' => 3,
                'stock_actual' => 5,
                'precio_compra' => 95.00,
                'precio_venta' => 130.00,
                'proveedor' => 'Distribuidora Premium',
                'ubicacion' => 'Almacén A, Estante 5',
                'estado' => 'activo',
                'fecha_compra' => '2024-02-25',
                'notas' => 'Compatible con Ryzen 3000 y 5000'
            ],
            [
                'codigo' => 'INV-007',
                'nombre' => 'Procesador AMD Ryzen 5 5600G',
                'descripcion' => 'Procesador AMD Ryzen 5 5600G con gráficos integrados Radeon',
                'categoria' => 'Componentes',
                'marca' => 'AMD',
                'modelo' => 'Ryzen 5 5600G',
                'serie' => 'SN333444555',
                'stock_minimo' => 2,
                'stock_actual' => 4,
                'precio_compra' => 180.00,
                'precio_venta' => 240.00,
                'proveedor' => 'Distribuidora Premium',
                'ubicacion' => 'Almacén A, Estante 6',
                'estado' => 'activo',
                'fecha_compra' => '2024-03-01',
                'notas' => 'Procesador con gráficos integrados'
            ],

            // PERIFÉRICOS
            [
                'codigo' => 'INV-008',
                'nombre' => 'Mouse Inalámbrico Logitech',
                'descripcion' => 'Mouse inalámbrico con sensor óptico de alta precisión',
                'categoria' => 'Periféricos',
                'marca' => 'Logitech',
                'modelo' => 'M185',
                'serie' => 'SN456789123',
                'stock_minimo' => 8,
                'stock_actual' => 3,
                'precio_compra' => 12.00,
                'precio_venta' => 18.00,
                'proveedor' => 'Distribuidora ABC',
                'ubicacion' => 'Almacén B, Estante 1',
                'estado' => 'activo',
                'fecha_compra' => '2024-01-10',
                'notas' => 'Stock bajo, reabastecer pronto'
            ],
            [
                'codigo' => 'INV-009',
                'nombre' => 'Teclado Mecánico RGB',
                'descripcion' => 'Teclado mecánico con switches Cherry MX y retroiluminación RGB',
                'categoria' => 'Periféricos',
                'marca' => 'Corsair',
                'modelo' => 'K70 RGB',
                'serie' => 'SN789123456',
                'stock_minimo' => 3,
                'stock_actual' => 0,
                'precio_compra' => 80.00,
                'precio_venta' => 120.00,
                'proveedor' => 'Distribuidora Premium',
                'ubicacion' => 'Almacén B, Estante 2',
                'estado' => 'agotado',
                'fecha_compra' => '2024-01-05',
                'notas' => 'Producto agotado, pedido en camino'
            ],
            [
                'codigo' => 'INV-010',
                'nombre' => 'Monitor LED 24 pulgadas',
                'descripcion' => 'Monitor LED Samsung de 24 pulgadas, Full HD 1920x1080, 60Hz',
                'categoria' => 'Periféricos',
                'marca' => 'Samsung',
                'modelo' => 'F24T450FQ',
                'serie' => 'SN666777888',
                'stock_minimo' => 4,
                'stock_actual' => 6,
                'precio_compra' => 120.00,
                'precio_venta' => 160.00,
                'proveedor' => 'Distribuidora ABC',
                'ubicacion' => 'Almacén B, Estante 3',
                'estado' => 'activo',
                'fecha_compra' => '2024-03-05',
                'notas' => 'Monitor básico para oficina'
            ],
            [
                'codigo' => 'INV-011',
                'nombre' => 'Webcam HD 1080p',
                'descripcion' => 'Webcam Logitech C920 HD Pro con micrófono integrado',
                'categoria' => 'Periféricos',
                'marca' => 'Logitech',
                'modelo' => 'C920 HD Pro',
                'serie' => 'SN999000111',
                'stock_minimo' => 6,
                'stock_actual' => 9,
                'precio_compra' => 65.00,
                'precio_venta' => 85.00,
                'proveedor' => 'Distribuidora ABC',
                'ubicacion' => 'Almacén B, Estante 4',
                'estado' => 'activo',
                'fecha_compra' => '2024-03-10',
                'notas' => 'Ideal para videoconferencias'
            ],

            // SOFTWARE Y LICENCIAS
            [
                'codigo' => 'INV-012',
                'nombre' => 'Windows 11 Pro',
                'descripcion' => 'Licencia de Windows 11 Professional para un equipo',
                'categoria' => 'Software',
                'marca' => 'Microsoft',
                'modelo' => 'Windows 11 Pro',
                'serie' => 'LIC-W11-PRO-001',
                'stock_minimo' => 5,
                'stock_actual' => 12,
                'precio_compra' => 120.00,
                'precio_venta' => 180.00,
                'proveedor' => 'Microsoft Partner',
                'ubicacion' => 'Almacén C, Estante 1',
                'estado' => 'activo',
                'fecha_compra' => '2024-01-25',
                'notas' => 'Licencias digitales, entregar por email'
            ],
            [
                'codigo' => 'INV-013',
                'nombre' => 'Office 365 Personal',
                'descripcion' => 'Licencia anual de Microsoft Office 365 Personal',
                'categoria' => 'Software',
                'marca' => 'Microsoft',
                'modelo' => 'Office 365 Personal',
                'serie' => 'LIC-O365-PER-001',
                'stock_minimo' => 8,
                'stock_actual' => 15,
                'precio_compra' => 45.00,
                'precio_venta' => 65.00,
                'proveedor' => 'Microsoft Partner',
                'ubicacion' => 'Almacén C, Estante 1',
                'estado' => 'activo',
                'fecha_compra' => '2024-03-15',
                'notas' => 'Licencia anual renovable'
            ],
            [
                'codigo' => 'INV-014',
                'nombre' => 'Antivirus Kaspersky Total Security',
                'descripcion' => 'Licencia de 1 año para Kaspersky Total Security',
                'categoria' => 'Software',
                'marca' => 'Kaspersky',
                'modelo' => 'Total Security 1YR',
                'serie' => 'LIC-KAS-TS-001',
                'stock_minimo' => 10,
                'stock_actual' => 20,
                'precio_compra' => 25.00,
                'precio_venta' => 35.00,
                'proveedor' => 'Kaspersky Partner',
                'ubicacion' => 'Almacén C, Estante 2',
                'estado' => 'activo',
                'fecha_compra' => '2024-03-20',
                'notas' => 'Protección completa para 1 año'
            ],

            // HERRAMIENTAS DE REPARACIÓN
            [
                'codigo' => 'INV-015',
                'nombre' => 'Destornillador Phillips',
                'descripcion' => 'Destornillador Phillips de precisión para trabajos de reparación',
                'categoria' => 'Herramientas',
                'marca' => 'Stanley',
                'modelo' => 'PH-1',
                'serie' => 'SN111222333',
                'stock_minimo' => 15,
                'stock_actual' => 8,
                'precio_compra' => 8.00,
                'precio_venta' => 12.00,
                'proveedor' => 'Ferretería Central',
                'ubicacion' => 'Almacén D, Estante 1',
                'estado' => 'activo',
                'fecha_compra' => '2024-01-30',
                'notas' => 'Herramienta básica para reparaciones'
            ],
            [
                'codigo' => 'INV-016',
                'nombre' => 'Juego de Destornilladores',
                'descripcion' => 'Juego completo de destornilladores de precisión para electrónicos',
                'categoria' => 'Herramientas',
                'marca' => 'iFixit',
                'modelo' => 'Precision Set',
                'serie' => 'SN222333444',
                'stock_minimo' => 5,
                'stock_actual' => 12,
                'precio_compra' => 35.00,
                'precio_venta' => 50.00,
                'proveedor' => 'Ferretería Central',
                'ubicacion' => 'Almacén D, Estante 1',
                'estado' => 'activo',
                'fecha_compra' => '2024-03-25',
                'notas' => 'Kit profesional de reparación'
            ],
            [
                'codigo' => 'INV-017',
                'nombre' => 'Pasta Térmica Arctic MX-4',
                'descripcion' => 'Pasta térmica de alta calidad para procesadores y GPUs',
                'categoria' => 'Herramientas',
                'marca' => 'Arctic',
                'modelo' => 'MX-4 4g',
                'serie' => 'SN333444555',
                'stock_minimo' => 20,
                'stock_actual' => 35,
                'precio_compra' => 6.00,
                'precio_venta' => 10.00,
                'proveedor' => 'Ferretería Central',
                'ubicacion' => 'Almacén D, Estante 2',
                'estado' => 'activo',
                'fecha_compra' => '2024-03-30',
                'notas' => 'Conductividad térmica excelente'
            ],
            [
                'codigo' => 'INV-018',
                'nombre' => 'Multímetro Digital',
                'descripcion' => 'Multímetro digital Fluke para mediciones eléctricas',
                'categoria' => 'Herramientas',
                'marca' => 'Fluke',
                'modelo' => '101',
                'serie' => 'SN444555666',
                'stock_minimo' => 3,
                'stock_actual' => 2,
                'precio_compra' => 85.00,
                'precio_venta' => 120.00,
                'proveedor' => 'Ferretería Central',
                'ubicacion' => 'Almacén D, Estante 3',
                'estado' => 'activo',
                'fecha_compra' => '2024-04-01',
                'notas' => 'Herramienta profesional de medición'
            ],

            // CONSUMIBLES Y CABLES
            [
                'codigo' => 'INV-019',
                'nombre' => 'Cable HDMI 2.0',
                'descripcion' => 'Cable HDMI de alta velocidad para 4K y HDR',
                'categoria' => 'Consumibles',
                'marca' => 'Belkin',
                'modelo' => 'HDMI-2.0-2M',
                'serie' => 'SN444555666',
                'stock_minimo' => 20,
                'stock_actual' => 35,
                'precio_compra' => 5.00,
                'precio_venta' => 8.00,
                'proveedor' => 'Distribuidora de Cables',
                'ubicacion' => 'Almacén E, Estante 1',
                'estado' => 'activo',
                'fecha_compra' => '2024-02-01',
                'notas' => 'Cable de 2 metros, alta calidad'
            ],
            [
                'codigo' => 'INV-020',
                'nombre' => 'Cable USB-C a USB-A',
                'descripcion' => 'Cable USB-C a USB-A de 1 metro para transferencia de datos',
                'categoria' => 'Consumibles',
                'marca' => 'Anker',
                'modelo' => 'USB-C-Cable-1M',
                'serie' => 'SN555666777',
                'stock_minimo' => 25,
                'stock_actual' => 40,
                'precio_compra' => 4.00,
                'precio_venta' => 6.00,
                'proveedor' => 'Distribuidora de Cables',
                'ubicacion' => 'Almacén E, Estante 1',
                'estado' => 'activo',
                'fecha_compra' => '2024-04-05',
                'notas' => 'Cable de transferencia rápida'
            ],
            [
                'codigo' => 'INV-021',
                'nombre' => 'Cable Ethernet Cat6',
                'descripcion' => 'Cable Ethernet Cat6 de 3 metros para conexión de red',
                'categoria' => 'Consumibles',
                'marca' => 'TP-Link',
                'modelo' => 'CAT6-3M',
                'serie' => 'SN666777888',
                'stock_minimo' => 15,
                'stock_actual' => 28,
                'precio_compra' => 3.50,
                'precio_venta' => 5.50,
                'proveedor' => 'Distribuidora de Cables',
                'ubicacion' => 'Almacén E, Estante 2',
                'estado' => 'activo',
                'fecha_compra' => '2024-04-10',
                'notas' => 'Cable de red de alta velocidad'
            ],
            [
                'codigo' => 'INV-022',
                'nombre' => 'Adaptador USB-C a HDMI',
                'descripcion' => 'Adaptador USB-C a HDMI para conectar dispositivos a monitores',
                'categoria' => 'Consumibles',
                'marca' => 'UGREEN',
                'modelo' => 'USB-C-HDMI',
                'serie' => 'SN777888999',
                'stock_minimo' => 8,
                'stock_actual' => 12,
                'precio_compra' => 15.00,
                'precio_venta' => 22.00,
                'proveedor' => 'Distribuidora de Cables',
                'ubicacion' => 'Almacén E, Estante 3',
                'estado' => 'activo',
                'fecha_compra' => '2024-04-15',
                'notas' => 'Adaptador de video de alta calidad'
            ],

            // EQUIPOS COMPLETOS
            [
                'codigo' => 'INV-023',
                'nombre' => 'Laptop HP Pavilion',
                'descripcion' => 'Laptop HP Pavilion con procesador Intel i5 y 8GB RAM',
                'categoria' => 'Equipos',
                'marca' => 'HP',
                'modelo' => 'Pavilion 15',
                'serie' => 'SN777888999',
                'stock_minimo' => 2,
                'stock_actual' => 1,
                'precio_compra' => 450.00,
                'precio_venta' => 650.00,
                'proveedor' => 'HP Distributor',
                'ubicacion' => 'Almacén F, Estante 1',
                'estado' => 'activo',
                'fecha_compra' => '2024-02-05',
                'notas' => 'Equipo de demostración disponible'
            ],
            [
                'codigo' => 'INV-024',
                'nombre' => 'Desktop Gaming AMD',
                'descripcion' => 'PC Gaming armado con AMD Ryzen 5, 16GB RAM, RTX 3060',
                'categoria' => 'Equipos',
                'marca' => 'Custom Build',
                'modelo' => 'Gaming Pro',
                'serie' => 'SN888999000',
                'stock_minimo' => 1,
                'stock_actual' => 2,
                'precio_compra' => 850.00,
                'precio_venta' => 1200.00,
                'proveedor' => 'Custom PC Builder',
                'ubicacion' => 'Almacén F, Estante 2',
                'estado' => 'activo',
                'fecha_compra' => '2024-04-20',
                'notas' => 'PC gaming de alta gama'
            ],

            // IMPRESORAS Y PERIFÉRICOS
            [
                'codigo' => 'INV-025',
                'nombre' => 'Impresora HP LaserJet Pro',
                'descripcion' => 'Impresora láser HP LaserJet Pro M404n para oficina',
                'categoria' => 'Impresoras',
                'marca' => 'HP',
                'modelo' => 'LaserJet Pro M404n',
                'serie' => 'SN999000111',
                'stock_minimo' => 1,
                'stock_actual' => 2,
                'precio_compra' => 180.00,
                'precio_venta' => 250.00,
                'proveedor' => 'HP Distributor',
                'ubicacion' => 'Almacén G, Estante 1',
                'estado' => 'activo',
                'fecha_compra' => '2024-04-25',
                'notas' => 'Impresora láser monocromática'
            ],
            [
                'codigo' => 'INV-026',
                'nombre' => 'Tóner HP CF400A',
                'descripcion' => 'Cartucho de tóner HP CF400A para impresoras LaserJet Pro',
                'categoria' => 'Consumibles',
                'marca' => 'HP',
                'modelo' => 'CF400A',
                'serie' => 'SN000111222',
                'stock_minimo' => 10,
                'stock_actual' => 18,
                'precio_compra' => 45.00,
                'precio_venta' => 65.00,
                'proveedor' => 'HP Distributor',
                'ubicacion' => 'Almacén G, Estante 2',
                'estado' => 'activo',
                'fecha_compra' => '2024-04-30',
                'notas' => 'Tóner original HP'
            ],
            [
                'codigo' => 'INV-027',
                'nombre' => 'Router WiFi 6 TP-Link',
                'descripcion' => 'Router WiFi 6 TP-Link Archer AX73 para conexión inalámbrica de alta velocidad',
                'categoria' => 'Redes',
                'marca' => 'TP-Link',
                'modelo' => 'Archer AX73',
                'serie' => 'SN111222333',
                'stock_minimo' => 3,
                'stock_actual' => 5,
                'precio_compra' => 120.00,
                'precio_venta' => 160.00,
                'proveedor' => 'TP-Link Distributor',
                'ubicacion' => 'Almacén H, Estante 1',
                'estado' => 'activo',
                'fecha_compra' => '2024-05-01',
                'notas' => 'Router WiFi 6 de última generación'
            ],

            // PRODUCTOS CON STOCK BAJO O AGOTADO
            [
                'codigo' => 'INV-028',
                'nombre' => 'Batería Laptop Dell',
                'descripcion' => 'Batería de repuesto para laptops Dell Inspiron 15 3000',
                'categoria' => 'Componentes',
                'marca' => 'Dell',
                'modelo' => 'Inspiron 15 3000',
                'serie' => 'SN222333444',
                'stock_minimo' => 5,
                'stock_actual' => 1,
                'precio_compra' => 35.00,
                'precio_venta' => 50.00,
                'proveedor' => 'Dell Distributor',
                'ubicacion' => 'Almacén A, Estante 7',
                'estado' => 'activo',
                'fecha_compra' => '2024-05-05',
                'notas' => 'Stock muy bajo, reabastecer urgentemente'
            ],
            [
                'codigo' => 'INV-029',
                'nombre' => 'Pantalla Laptop 15.6"',
                'descripcion' => 'Pantalla LCD 15.6 pulgadas Full HD para laptops',
                'categoria' => 'Componentes',
                'marca' => 'Generic',
                'modelo' => 'LCD-15.6-FHD',
                'serie' => 'SN333444555',
                'stock_minimo' => 3,
                'stock_actual' => 0,
                'precio_compra' => 85.00,
                'precio_venta' => 120.00,
                'proveedor' => 'LCD Distributor',
                'ubicacion' => 'Almacén A, Estante 8',
                'estado' => 'agotado',
                'fecha_compra' => '2024-05-10',
                'notas' => 'Producto agotado, pedido en camino'
            ],
            [
                'codigo' => 'INV-030',
                'nombre' => 'Teclado para Laptop',
                'descripcion' => 'Teclado de repuesto para laptops HP Pavilion 15',
                'categoria' => 'Componentes',
                'marca' => 'HP',
                'modelo' => 'Pavilion 15 Keyboard',
                'serie' => 'SN444555666',
                'stock_minimo' => 4,
                'stock_actual' => 2,
                'precio_compra' => 25.00,
                'precio_venta' => 35.00,
                'proveedor' => 'HP Distributor',
                'ubicacion' => 'Almacén A, Estante 9',
                'estado' => 'activo',
                'fecha_compra' => '2024-05-15',
                'notas' => 'Stock bajo, verificar disponibilidad'
            ]
        ];

        foreach ($items as $item) {
            Inventario::create($item);
        }

        $this->command->info('Inventario poblado exitosamente: ' . count($items) . ' productos insertados.');
    }
}
